spring.application.name: auth_test

jwt:
  auth:
    enabled: true
    secret: f784e8f9bc02eb6e5b7f9c356be88bc2bc00209ed40df1e075b995f5a3d77829df9f7cb1dbcf97f98c4616ec828b1b83064849413a2306ddaa1155972eadad6d
    expiration: 86400000                    # Dur�e de validit� en millisecondes (24h par d�faut)
    header: Authorization                   # Nom du header HTTP (d�faut: Authorization)
    prefix: "Bearer "
    issuer: mon-application
    blacklist-enabled: false

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/auth_test
    username: root
    password: JC001



  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
      format_sql: true
