server:
  port: 8081

project:
  build:
    directory: target/

info:
  app:
    name: "Auth service"
    version: "1.0.0"
    description: "Microservice d'authentification"

spring:
  config:
    import:
    - secrets.yaml
    
  application:
    name: AUTH-SERVICE
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      
    
logging:
  level: 
    root: error

